name: Build and Publish package
on:
  push:
    branches: [ snomed-master ]
  workflow_dispatch:

jobs:
  build-publish-package:
    name: Build and Publish package
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: nexus-sonatype
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Install compass
        run: |
          sudo gem install compass -v 1.0.3
      - name: Build and deploy with Maven
        run: ./mvnw --no-transfer-progress clean -U deploy
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  trigger:
    name: Trigger Deployment Workflow in Distro Bahmni
    needs:
      - build-publish-package
    runs-on: ubuntu-latest
    env:
      ORG_NAME: Bahmni
      REPOSITORY_NAME: openmrs-distro-bahmni
      ENVIRONMENT: dev
    steps:
      - name: Create workflow_dispatch
        run: |
          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/actions/workflows/build_publish_openmrs.yml/dispatches -d '{"ref":"snomed-master","inputs":{}')
          if [ $trigger_result == 204 ];then
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
          else
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
            cat trigger_response.txt
            exit 1
          fi
